### ISSUE TITLE
Syntax highlight & more configurations & ...

### ISSUE THREAD

**Issue by neilsustc** [shibayan/WinQuickLook#1]
Amazing! Thanks for your great work. 👍 

I think it could be better to have these,

1. syntax highlight for common programming languages
2. provide some options (such as font size, 13px is not appropriate for 1080p)

Another thing, I can add `.py`, `.json` etc. into [`_supportFormats`](https://github.com/shibayan/WinQuickLook/blob/master/src/WinQuickLook/Handlers/TextPreviewHandler.cs#L48) to support more formats that I need. BUT I think if it's planed to separate source code file from plain text file (to provide syntax highlight), or make the supported file formats configurable, I can wait to know how you think about it.

I‘d be really like to contribute to this program.

**Comment by shibayan** [comment]
Syntax highlight feature is testing now. It use JavaScript syntax highlight library.

![image](https://cloud.githubusercontent.com/assets/1356444/23910528/668d251e-091d-11e7-9150-18ccbc685355.png)

**Comment by neilsustc** [comment]
It looks pretty cool 😄
