### ISSUE TITLE
Broken Download Command in the Readme File

### ISSUE THREAD

**Issue by salihozkara** [shibayan/WinQuickLook#188]
There is an issue with the download command found in the Readme file, as it is not working properly. A screenshot of the terminal has been provided to show the error message.

![image](https://user-images.githubusercontent.com/58659931/218160777-6e787dd1-92aa-4082-8b96-2421d4bf9162.png)

**Comment by shibayan** [comment]
The cause is unknown, but it appears that the Microsoft Store search index is corrupted. Currently only package ID are available.
