### ISSUE TITLE
Open with associated program not working

### ISSUE THREAD

**Issue by RohanKailthya** [shibayan/WinQuickLook#32]
When i click the top left icon to open with the associated program i get the warning of "Can't open this file with associated program". 

Windows version : Windows 10 2004 (x64).

![Untitled](https://user-images.githubusercontent.com/50741588/85159813-95abb080-b27b-11ea-8a7d-21f66e8daf74.jpg)

**Comment by shibayan** [comment]
Is it occurring in all file formats? Please let me know if this happens with only certain file formats.

**Comment by RohanKailthya** [comment]
> Is it occurring in all file formats? Please let me know if this happens with only certain file formats.

I tried on several file formats and it occurred in all of them.

**Comment by shibayan** [comment]
Thanks for the report. I was able to reproduce the problem and will fix it.
