### ISSUE TITLE
[Bug] Multiple processes opening

### ISSUE THREAD

**Issue by lemonnuggets** [shibayan/WinQuickLook#64]
While trying to preview a file I clicked the spacebar multiple times and once I saw the preview I decided I wanted to delete the file. But I think since I pressed the spacebar multiple instances of WinQuickLook must have opened or something like that because this is what showed up when I tried to delete the file.

![image](https://user-images.githubusercontent.com/63046776/105759260-3e3e9300-5f76-11eb-9958-a9f1ccf2c592.png)

Sure enough, when I checked the task manager, WinQuickLook was still running despite me having closed the window and made sure there wasn't any window of it open.
![image](https://user-images.githubusercontent.com/63046776/105759379-67f7ba00-5f76-11eb-9c1f-44c174133046.png)
 Once I killed the process everything returned to normal.

**Comment by shibayan** [comment]
It is a specification that the process will continue to run even after the preview is hidden.

The rare locking of files has been fixed.
